In [1]:
import numpy as np

In [2]:
A = np.array([[3,2], [4,1]])
A

array([[3, 2],
       [4, 1]])

In [3]:
autovalores, autovectores = np.linalg.eig(A)
autovalores, autovectores

(array([ 5., -1.]),
 array([[ 0.70710678, -0.4472136 ],
        [ 0.70710678,  0.89442719]]))

## Primera forma

* Matriz cuadrada

$$A = B \cdot \lambda \cdot B^{-1}$$

In [7]:
A_calc = autovectores @ np.diag(autovalores) @ np.linalg.inv(autovectores)
A_calc

array([[3., 2.],
       [4., 1.]])

## Segunda Forma
* Cuando la matriz es simétrica

$$A = B \cdot \lambda \cdot B^{T}$$

In [9]:
A = np.array([[3,2], [2,3]])
A == A.T

array([[ True,  True],
       [ True,  True]])

In [11]:
autovalores, autovectores = np.linalg.eig(A)
autovalores, autovectores

(array([5., 1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))