In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
A = np.array([[3,7], [5,2]])
A

array([[3, 7],
       [5, 2]])

In [8]:
U, D, V = np.linalg.svd(A)
D

array([8.71337969, 3.32821489])

In [9]:
u1 = np.diag(D) @ U

In [10]:
U @ np.diag(D) @ V

array([[3., 7.],
       [5., 2.]])