In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3], [3,4,5]])
A

array([[1, 2, 3],
       [3, 4, 5]])

In [3]:
U, D, V = np.linalg.svd(A)
U,D,V

(array([[-0.46410668,  0.88577931],
        [-0.88577931, -0.46410668]]),
 array([7.97638869, 0.61418515]),
 array([[-0.39133557, -0.5605708 , -0.72980603],
        [-0.8247362 , -0.13817999,  0.54837623],
        [ 0.40824829, -0.81649658,  0.40824829]]))

In [4]:
D_aux = np.concatenate((np.diag(D), np.zeros((2,1))), axis=1)
A_calc = U @ D_aux @ V
A_calc

array([[1., 2., 3.],
       [3., 4., 5.]])