In [144]:
import numpy as np
np.set_printoptions(suppress=True)

## Teorema de pseudoinversa de _Moore_
$$A \cdot A_{\text{pse}} \approx \text{Identidad}$$

# Método SVD

In [145]:
A = np.array([
    [2,3],
    [5,7],
    [11,13]
])
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [146]:
np.set_printoptions(precision=4, suppress=True)

In [147]:
U, D, V = np.linalg.svd(A)
print("U", U, "\nD",D, "\nV", V, sep="\n")

U
[[-0.185  -0.4728 -0.8615]
 [-0.4425 -0.7427  0.5026]
 [-0.8775  0.4742 -0.0718]]

D
[19.4032  0.7178]

V
[[-0.6306 -0.7761]
 [ 0.7761 -0.6306]]


In [148]:
U, D, V = np.linalg.svd(A)

In [149]:
U.shape

(3, 3)

In [150]:
V.T.shape

(2, 2)

### Cálculo de la inversa de D

In [151]:
D_pse = np.zeros_like(A, dtype=np.float_).T
print(D_pse)

[[0. 0. 0.]
 [0. 0. 0.]]


In [152]:
print("Valores a reemplazar")
print(D_pse[:D.shape[0], :D.shape[0]])

Valores a reemplazar
[[0. 0.]
 [0. 0.]]


In [153]:
print("Valores a ubicar en D_pse")
print(np.linalg.inv(np.diag(D)))

Valores a ubicar en D_pse
[[0.0515 0.    ]
 [0.     1.3931]]


In [154]:
D_pse = np.zeros_like(A, dtype=np.float_).T
D_pse[:D.shape[0],:D.shape[0]] = np.linalg.inv(np.diag(D))
print(D_pse)

[[0.0515 0.     0.    ]
 [0.     1.3931 0.    ]]


### Cálculo de la inversa

In [172]:
A_pse = V.T @ D_pse @ U.T
A_pse

array([[-0.5052, -0.7887,  0.5412],
       [ 0.4227,  0.6701, -0.3814]])

In [181]:
D_aux = np.concatenate( (np.diag(D), [[0,0]]), axis=0)
print(D_aux)
print(U @ D_aux @ V)

[[19.4032  0.    ]
 [ 0.      0.7178]
 [ 0.      0.    ]]
[[ 2.  3.]
 [ 5.  7.]
 [11. 13.]]


In [182]:
print(D_pse)
print(V.T @ D_pse @ U.T)

[[0.0515 0.     0.    ]
 [0.     1.3931 0.    ]]
[[-0.5052 -0.7887  0.5412]
 [ 0.4227  0.6701 -0.3814]]


In [173]:
np.linalg.pinv(A)

array([[-0.5052, -0.7887,  0.5412],
       [ 0.4227,  0.6701, -0.3814]])

In [155]:
D_pse[:D.shape[0],:D.shape[0]] = np.linalg.inv(np.diag(D))
D_pse

array([[0.0515, 0.    , 0.    ],
       [0.    , 1.3931, 0.    ]])

## Verificación

In [184]:
np.linalg.pinv(A) @ A

array([[ 1., -0.],
       [ 0.,  1.]])

In [185]:
A_pse @ A

array([[ 1., -0.],
       [ 0.,  1.]])

# Pseudo inversa 2

Es más rápida pero inxacta.

In [189]:
A_pse_2 = np.linalg.inv(A.T @ A) @ A.T
A_pse_2

array([[-0.5052, -0.7887,  0.5412],
       [ 0.4227,  0.6701, -0.3814]])